# Generated by Django 5.2.4 on 2025-08-02 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100, verbose_name='Предмет')),
                ('teacher', models.CharField(max_length=100, verbose_name='Учител')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignmentDesc',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dueDate',
            field=models.DateField(verbose_name='Крайна дата'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.subject'),
        ),
    ]
