# Generated by Django 5.2.4 on 2025-08-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_subject_remove_assignment_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='subject',
            new_name='subjectConn',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subjectName',
            new_name='subject',
        ),
    ]
