# Generated by Django 5.2.4 on 2025-08-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_subject_assignment_subjectconn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='subjectName',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subjectConn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.subject', verbose_name='Предмет'),
        ),
    ]
