# Generated by Django 5.2.4 on 2025-08-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_rename_subject_subject_subjectname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignmentDesc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subjectConn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
    ]
